#############################################################################
# Makefile for building: Focus
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  Focus.pro
# Template: app
# Command: /usr/local/Qt-5.4.1/bin/qmake -o Makefile Focus.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-gcc
CXX           = /home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/mnt/rasp-pi-rootfs -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/mnt/rasp-pi-rootfs -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I. -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQuick -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtWidgets -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore -I. -I/mnt/rasp-pi-rootfs/opt/vc/include -I/mnt/rasp-pi-rootfs/opt/vc/include/interface/vcos/pthreads -I/mnt/rasp-pi-rootfs/opt/vc/include/interface/vmcs_host/linux -I/usr/local/Qt-5.4.1/mkspecs/devices/linux-rasp-pi-g++
QMAKE         = /usr/local/Qt-5.4.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Focus1.0.0
DISTDIR = /home/slimani/QTPROJECT/Focus/.tmp/Focus1.0.0
LINK          = /home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-rpath-link,/mnt/rasp-pi-rootfs/opt/vc/lib -Wl,-rpath-link,/mnt/rasp-pi-rootfs/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/mnt/rasp-pi-rootfs/lib/arm-linux-gnueabihf --sysroot=/mnt/rasp-pi-rootfs -Wl,-O1 -Wl,-rpath,/usr/local/Qt-5.4.1/lib
LIBS          = $(SUBLIBS) -L/mnt/rasp-pi-rootfs/opt/vc/lib -L/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib -lQt5Quick -L/usr/local/Qt-5.4.1/lib -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5DBus -lQt5Core -lGLESv2 -lpthread 
AR            = /home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp \
		qrc_images.cpp \
		moc_Media_bluetooth.cpp \
		moc_Ofono_bluetooth.cpp
OBJECTS       = main.o \
		qrc_qml.o \
		qrc_images.o \
		moc_Media_bluetooth.o \
		moc_Ofono_bluetooth.o
DIST          = /usr/local/Qt-5.4.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.4.1/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.4.1/mkspecs/qdevice.pri \
		/usr/local/Qt-5.4.1/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.4.1/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/Qt-5.4.1/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/Qt-5.4.1/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/Qt-5.4.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.4.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/usr/local/Qt-5.4.1/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/local/Qt-5.4.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/dbuscommon.pri \
		/usr/local/Qt-5.4.1/mkspecs/features/dbusinterfaces.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/dbusadaptors.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/uic.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/lex.prf \
		Focus.pro Media_bluetooth.h \
		Ofono_bluetooth.h main.cpp
QMAKE_TARGET  = Focus
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Focus


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Focus.pro /usr/local/Qt-5.4.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf /usr/local/Qt-5.4.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.4.1/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.4.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.4.1/mkspecs/qdevice.pri \
		/usr/local/Qt-5.4.1/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.4.1/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/Qt-5.4.1/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/Qt-5.4.1/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/Qt-5.4.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.4.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.4.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/usr/local/Qt-5.4.1/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/local/Qt-5.4.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/dbuscommon.pri \
		/usr/local/Qt-5.4.1/mkspecs/features/dbusinterfaces.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/dbusadaptors.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/uic.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.4.1/mkspecs/features/lex.prf \
		Focus.pro \
		qml.qrc \
		images.qrc \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Quick.prl \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Gui.prl \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Core.prl \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Qml.prl \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Network.prl \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Widgets.prl \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5DBus.prl
	$(QMAKE) -o Makefile Focus.pro
/usr/local/Qt-5.4.1/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.4.1/mkspecs/common/shell-unix.conf:
/usr/local/Qt-5.4.1/mkspecs/common/unix.conf:
/usr/local/Qt-5.4.1/mkspecs/common/linux.conf:
/usr/local/Qt-5.4.1/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.4.1/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.4.1/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.4.1/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.4.1/mkspecs/qdevice.pri:
/usr/local/Qt-5.4.1/mkspecs/features/device_config.prf:
/usr/local/Qt-5.4.1/mkspecs/devices/common/linux_device_pre.conf:
/usr/local/Qt-5.4.1/mkspecs/devices/common/linux_device_post.conf:
/usr/local/Qt-5.4.1/mkspecs/devices/common/linux_arm_device_post.conf:
/usr/local/Qt-5.4.1/mkspecs/qconfig.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_enginio.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.4.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt-5.4.1/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.4.1/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.4.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf:
/usr/local/Qt-5.4.1/mkspecs/features/spec_post.prf:
/usr/local/Qt-5.4.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.4.1/mkspecs/features/default_pre.prf:
deployment.pri:
/usr/local/Qt-5.4.1/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.4.1/mkspecs/features/default_post.prf:
/usr/local/Qt-5.4.1/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.4.1/mkspecs/features/qt.prf:
/usr/local/Qt-5.4.1/mkspecs/features/resources.prf:
/usr/local/Qt-5.4.1/mkspecs/features/moc.prf:
/usr/local/Qt-5.4.1/mkspecs/features/dbuscommon.pri:
/usr/local/Qt-5.4.1/mkspecs/features/dbusinterfaces.prf:
/usr/local/Qt-5.4.1/mkspecs/features/dbusadaptors.prf:
/usr/local/Qt-5.4.1/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.4.1/mkspecs/features/uic.prf:
/usr/local/Qt-5.4.1/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.4.1/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.4.1/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.4.1/mkspecs/features/yacc.prf:
/usr/local/Qt-5.4.1/mkspecs/features/lex.prf:
Focus.pro:
qml.qrc:
images.qrc:
/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Quick.prl:
/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Gui.prl:
/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Core.prl:
/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Qml.prl:
/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Network.prl:
/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5Widgets.prl:
/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/lib/libQt5DBus.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Focus.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents Media_bluetooth.h Ofono_bluetooth.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp qrc_images.cpp
qrc_qml.cpp: qml.qrc \
		navigation/InputBox.qml \
		navigation/map.qml \
		multimedia/ScrollIndicator.qml \
		multimedia/Media.qml \
		multimedia/MainMusic.qml \
		multimedia/MusicModel.qml \
		multimedia/MainMusic2.qml \
		Bluetooth/Button.qml \
		Bluetooth/Dialpad.qml \
		Bluetooth/Media-Bluetooth.qml \
		Bluetooth/DialButton.qml \
		internet/rechercher.qml \
		internet/linkedin.qml \
		internet/gmail.qml \
		internet/youtube.qml \
		internet/twitter.qml \
		internet/facebook.qml \
		internet/google.qml \
		internet/acceuill.qml \
		home/Button.qml \
		home/Utils.js \
		home/TrackItem.qml \
		home/NewItem.qml \
		home/MainItem.qml \
		home/SingleItem.qml \
		home/Focus_IVI.qml
	/usr/local/Qt-5.4.1/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

qrc_images.cpp: images.qrc \
		Images/facebook_2.png \
		Images/bluetooth.png \
		Images/sd.png \
		Images/indicator.png \
		Images/radio8.png \
		Images/audio_volume_high.png \
		Images/icon_keyboard.png \
		Images/youtube_icon.png \
		Images/Phone-icon.png \
		Images/slr_camera.png \
		Images/design6.png \
		Images/audio_volume_muted.png \
		Images/home.png \
		Images/playList.png \
		Images/mp3_cd.png \
		Images/icon_next.png \
		Images/aa.png \
		Images/256px-Linkedin_icon.svg_.png \
		Images/phone.png \
		Images/sdCard.png \
		Images/icon_routepoint.png \
		Images/2.png \
		Images/scroll_indicator.png \
		Images/icon_prev.png \
		Images/zoomout.png \
		Images/musc.jpg \
		Images/icon_play.png \
		Images/fuulScreen.png \
		Images/twitter.png \
		Images/icon_back.png \
		Images/usb.png \
		Images/background.jpg \
		Images/navigation5.png \
		Images/icon_zoom_out.png \
		Images/gallery.png \
		Images/icon_rr.png \
		Images/navigation.png \
		Images/button_pause.png \
		Images/icon_ff.png \
		Images/button_rewind.png \
		Images/maps-icon.png \
		Images/online_fm_radio.png \
		Images/icon_zoom_in.png \
		Images/icon_forward.png \
		Images/usb2.png \
		Images/icon_internet.png \
		Images/icon_cancel.png \
		Images/device.png \
		Images/icon_url.png \
		Images/search.png \
		Images/icon_ok.png \
		Images/icon_pause.png \
		Images/zoomin.png \
		Images/button_forward.png \
		Images/Communication-gmail-icon.png \
		Images/Google-Mobile-App-Logo.png \
		Images/son.mp3 \
		Images/images.qrc \
		Images/Phone.png \
		Images/icon_locate.png \
		Images/media1.png \
		Images/network_connection_w.png \
		Images/multimedia.png \
		Images/icon_reload.png \
		Images/Bluetooth.png \
		Images/internet.png \
		Images/Twitter_logo_png-4.png \
		Images/button_play.png \
		Images/internet4.png \
		Images/fullScreen.png
	/usr/local/Qt-5.4.1/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_Media_bluetooth.cpp moc_Ofono_bluetooth.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Media_bluetooth.cpp moc_Ofono_bluetooth.cpp
moc_Media_bluetooth.cpp: /mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/QDBusMessage \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusmessage.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusmacros.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qglobal.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qconfig.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfeatures.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsystemdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qprocessordetection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcompilerdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtypeinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtypetraits.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsysinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlogging.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qflags.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbasicatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_bootstrap.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qgenericatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_msvc.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_armv7.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_armv6.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_armv5.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_ia64.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_mips.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_x86.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_cxx11.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_gcc.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_unix.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qglobalstatic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmutex.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qnumeric.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmetatype.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbytearray.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qrefcount.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qnamespace.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qarraydata.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstring.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qchar.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringbuilder.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvarlengtharray.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcontainerfwd.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qalgorithms.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qisenum.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobjectdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobjectdefs_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvariant.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qiterator.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbytearraylist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmap.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpair.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qdebug.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qhash.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtextstream.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qiodevice.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobject.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcoreevent.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qscopedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobject_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlocale.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qshareddata.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvector.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpoint.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qset.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcontiguouscache.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringlist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qdatastream.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qregexp.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringmatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbuserror.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/QDBusConnection \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusconnection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QObject \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/QDBusInterface \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusinterface.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusabstractinterface.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusextratypes.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/QDBusArgument \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusargument.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QProcess \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qprocess.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QDebug \
		Media_bluetooth.h
	/usr/local/Qt-5.4.1/bin/moc $(DEFINES) -I/usr/local/Qt-5.4.1/mkspecs/devices/linux-rasp-pi-g++ -I/home/slimani/QTPROJECT/Focus -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQuick -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtWidgets -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include/c++/4.7.2 -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include/c++/4.7.2/arm-linux-gnueabihf -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include/c++/4.7.2/backward -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.7.2/include -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.7.2/include-fixed -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include -I/mnt/rasp-pi-rootfs/usr/include -I/mnt/rasp-pi-rootfs/usr/include/arm-linux-gnueabihf Media_bluetooth.h -o moc_Media_bluetooth.cpp

moc_Ofono_bluetooth.cpp: /mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QObject \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobject.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobjectdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qnamespace.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qglobal.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qconfig.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfeatures.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsystemdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qprocessordetection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcompilerdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtypeinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtypetraits.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsysinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlogging.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qflags.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbasicatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_bootstrap.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qgenericatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_msvc.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_armv7.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_armv6.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_armv5.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_ia64.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_mips.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_x86.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_cxx11.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_gcc.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_unix.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qglobalstatic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmutex.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qnumeric.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobjectdefs_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstring.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qchar.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbytearray.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qrefcount.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qarraydata.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringbuilder.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qalgorithms.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qiterator.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbytearraylist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcoreevent.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qscopedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmetatype.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvarlengtharray.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcontainerfwd.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qisenum.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobject_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QProcess \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qprocess.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qiodevice.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringlist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qdatastream.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpair.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qregexp.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringmatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qshareddata.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qhash.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QDebug \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qdebug.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmap.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtextstream.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlocale.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvariant.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvector.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpoint.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qset.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcontiguouscache.h \
		Ofono_bluetooth.h
	/usr/local/Qt-5.4.1/bin/moc $(DEFINES) -I/usr/local/Qt-5.4.1/mkspecs/devices/linux-rasp-pi-g++ -I/home/slimani/QTPROJECT/Focus -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQuick -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtWidgets -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus -I/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include/c++/4.7.2 -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include/c++/4.7.2/arm-linux-gnueabihf -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include/c++/4.7.2/backward -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.7.2/include -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.7.2/include-fixed -I/home/slimani/opt/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include -I/mnt/rasp-pi-rootfs/usr/include -I/mnt/rasp-pi-rootfs/usr/include/arm-linux-gnueabihf Ofono_bluetooth.h -o moc_Ofono_bluetooth.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtWidgets/QApplication \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtWidgets/qapplication.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcoreapplication.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qglobal.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qconfig.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfeatures.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsystemdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qprocessordetection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcompilerdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtypeinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtypetraits.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsysinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlogging.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qflags.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbasicatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_bootstrap.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qgenericatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_msvc.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_armv7.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_armv6.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_armv5.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_ia64.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_mips.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_x86.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_cxx11.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_gcc.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qatomic_unix.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qglobalstatic.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmutex.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qnumeric.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstring.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qchar.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbytearray.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qrefcount.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qnamespace.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qarraydata.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringbuilder.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobject.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobjectdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobjectdefs_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qalgorithms.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qiterator.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbytearraylist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcoreevent.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qscopedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmetatype.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvarlengtharray.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcontainerfwd.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qisenum.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobject_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qeventloop.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qwindowdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qwindowdefs_win.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpoint.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsize.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qcursor.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtWidgets/qdesktopwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtWidgets/qwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmargins.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qpaintdevice.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qrect.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qpalette.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qcolor.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qrgb.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringlist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qdatastream.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qiodevice.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpair.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qregexp.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringmatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qbrush.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvector.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qmatrix.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qpolygon.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qregion.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qline.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qtransform.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qpainterpath.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qimage.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qpixelformat.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qpixmap.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsharedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qshareddata.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qhash.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsharedpointer_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qfont.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qfontmetrics.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qfontinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtWidgets/qsizepolicy.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qkeysequence.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qevent.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvariant.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmap.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qdebug.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtextstream.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlocale.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qset.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcontiguouscache.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qurl.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qurlquery.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfile.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfiledevice.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qvector2d.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qtouchdevice.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qguiapplication.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtGui/qinputmethod.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/QQmlApplicationEngine \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlapplicationengine.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlengine.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qjsengine.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qjsvalue.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qtqmlglobal.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlerror.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmldebug.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/QtQml \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/QtQmlDepends \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QtCore \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QtCoreDepends \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qabstractanimation.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qanimationgroup.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qparallelanimationgroup.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpauseanimation.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpropertyanimation.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qvariantanimation.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qeasingcurve.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsequentialanimationgroup.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtextcodec.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qendian.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlibraryinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qdatetime.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbuffer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qdir.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfileinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qdiriterator.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfileselector.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QObject \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QStringList \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfilesystemwatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlockfile.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qloggingcategory.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qprocess.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qresource.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsavefile.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsettings.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstandardpaths.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstorageinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtemporarydir.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QScopedPointer \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtemporaryfile.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qabstractitemmodel.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qabstractproxymodel.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qidentityproxymodel.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qitemselectionmodel.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsortfilterproxymodel.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstringlistmodel.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qjsonarray.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qjsonvalue.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qjsondocument.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qjsonobject.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qabstracteventdispatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qabstractnativeeventfilter.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbasictimer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmath.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmetaobject.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmimedata.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qobjectcleanuphandler.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsharedmemory.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsignalmapper.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsocketnotifier.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsystemsemaphore.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtimer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtranslator.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qwineventnotifier.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmimedatabase.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmimetype.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfactoryinterface.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlibrary.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qplugin.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qpluginloader.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/quuid.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qabstractstate.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qabstracttransition.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qeventtransition.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfinalstate.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qhistorystate.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsignaltransition.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstate.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstatemachine.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qexception.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfuture.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfutureinterface.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qrunnable.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qresultstore.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfuturesynchronizer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qfuturewatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qreadwritelock.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qsemaphore.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qthread.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qthreadpool.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qthreadstorage.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qwaitcondition.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qarraydataops.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qarraydatapointer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbitarray.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qbytearraymatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcache.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcollator.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcommandlineoption.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcommandlineparser.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qcryptographichash.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qelapsedtimer.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qlinkedlist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qmessageauthenticationcode.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qqueue.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qregularexpression.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qscopedvaluerollback.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qstack.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtextboundaryfinder.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtimeline.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtimezone.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qxmlstream.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/qtcoreversion.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/QtNetwork \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/QtNetworkDepends \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qabstractnetworkcache.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkrequest.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QSharedDataPointer \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QString \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QUrl \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QVariant \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qhttpmultipart.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QByteArray \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QIODevice \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/QNetworkRequest \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkaccessmanager.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/QSslConfiguration \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qsslconfiguration.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qsslsocket.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qtcpsocket.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qabstractsocket.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qsslerror.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qsslcertificate.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qssl.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QFlags \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkcookie.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QList \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QMetaType \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkcookiejar.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkdiskcache.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkreply.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/QNetworkAccessManager \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkconfigmanager.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkconfiguration.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworksession.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkinterface.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qhostaddress.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qauthenticator.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qdnslookup.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qhostinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qnetworkproxy.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qlocalserver.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qlocalsocket.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qtcpserver.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qudpsocket.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qsslcertificateextension.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qsslcipher.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qsslkey.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtNetwork/qtnetworkversion.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qjsvalueiterator.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqml.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlprivate.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlparserstatus.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlpropertyvaluesource.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmllist.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlabstracturlinterceptor.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlcomponent.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlcontext.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlexpression.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlscriptstring.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlextensioninterface.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlextensionplugin.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlfile.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlfileselector.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/QQmlEngine \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlincubator.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlnetworkaccessmanagerfactory.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlproperty.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qqmlpropertymap.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QHash \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtQml/qtqmlversion.h \
		Media_bluetooth.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/QDBusMessage \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusmessage.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusmacros.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbuserror.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/QDBusConnection \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusconnection.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/QDBusInterface \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusinterface.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusabstractinterface.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusextratypes.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/QDBusArgument \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtDBus/qdbusargument.h \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QProcess \
		/mnt/rasp-pi-rootfs/usr/local/Qt-5.4.1/include/QtCore/QDebug \
		Ofono_bluetooth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_Media_bluetooth.o: moc_Media_bluetooth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Media_bluetooth.o moc_Media_bluetooth.cpp

moc_Ofono_bluetooth.o: moc_Ofono_bluetooth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Ofono_bluetooth.o moc_Ofono_bluetooth.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Focus/bin || mkdir -p $(INSTALL_ROOT)/opt/Focus/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/Focus/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/Focus/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/Focus/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Focus/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

